# These are supported funding model platforms

github: thqby
custom:
  - https://qr.alipay.com/fkx19566u7ctegoppmu5i13
  - https://github.com/thqby/vscode-autohotkey2-lsp/raw/main/pic/alipay.jpg
  - https://www.paypal.me/thqby
