# Adapted from GitHub issue comment code by george-gca on 2024-01-16
# https://github.com/prettier/prettier/issues/6885#issuecomment-1894252136

name: Prettier diff

on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']
  workflow_dispatch:
  # merge_group:

jobs:
  build:
    strategy:
      matrix:
        # AHK is built for Windows only, so we only build on Windows
        # As always, if community asks, community shall receive ;)
        os: [windows-latest]
        node-version: [20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - name: Run Prettier
        id: runPrettier
        # format is just `prettier --check .`
        run: npm run format
      - name:
        if: ${{ failure() }}
        # format:fix is just `prettier --write .`
        run: |
          npm run format:fix
          git diff
